name: Build pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build and test with maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: '[{"id": "github", "username": "javierolmo", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: melodia-service
          path: target/melodia-service.jar

  publish_in_dockerhub:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: melodia-service
          path: target/melodia-service.zip

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq melodia-service.zip -d melodia-service.jar

      - name: Set Release version env variable
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: javiolmo/melodia-service:latest

      - name: Push to Docker Hub version number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: javiolmo/melodia-service:${{ env.RELEASE_VERSION }}

  deploy:
    name: Deploy in server
    runs-on: ubuntu-latest
    needs: publish_in_dockerhub
    steps:

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
