name: Tests

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: '[{"id": "github", "username": "javierolmo", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: melodia-service
          path: target/melodia-service.jar

  publish_in_dockerhub:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: melodia-service
          path: target/melodia-service.jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: javiolmo/pfg-backend:latest